# baseURL: 'https://toestre.github.io/predigtplan/'
languageCode: 'de-de'
title: 'Predigtplan und -sammlung'

theme: "PaperMod"

#baseURL: "https://toestre.github.io/predigtplan/"
#title: Predigtplan und -sammlung
copyright: "© [toestre](https://github.com/toestre/predigtplan/contributors)"
theme: PaperMod

contentDir: "content"
mainsections: ["posts"]


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Predigtplan und -sammlung"
  author: Tilmann
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  # comments: false
  #images: ["images/papermod-cover.png"]

  # profileMode:
  #   enabled: false
  #   title: PaperMod
  #   imageUrl: "#"
  #   imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    # buttons:
    #   - name: Archives
    #     url: archives
    #   - name: Tags
        # url: tags

  # homeInfoParams:
  #   Title: "Predigtplan"
  #   Content: >
  #     👋 Welcome to demo page of Hugo's theme PaperMod!

  #     - **PaperMod**  is designed to be clean and simple but fast and responsive theme with useful feature-set that enhances UX.

  #     - Feel free to show your support by giving us a star 🌟 on GitHub and sharing with your friends and social media .

  #     - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper/tree/4330c8b12aa48bfdecbcad6ad66145f679a430b3).

markup:
  markup.goldmark:
    markup.goldmark.renderer:
      unsafe: true
  markup.highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNos: true
    noClasses: false

module:
  mounts:
    - source: "content/posts"
      target: "content/posts"
    - source: "content"
      target: "content"